version: '3.7'

services:

  kameleoon:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(curl --silent --fail http://localhost:8080/web-kameleoon/actuator/health | jq -r '.status') = \"UP\" ]" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s